version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db_test:
    image: postgres:13.7-alpine
    volumes:
      - db_test_data:/var/lib/postgresql/data_test
    ports:
      - 5434:5434

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
      - db_test

    volumes:
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db_test
      - server

volumes:
  db_data:
  db_test_data:
