version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - db
    volumes:
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_NAME=shareit
      - DB_PORT=5432

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server

volumes:
  db_data:
